import 'modern-css-reset'
import '@/styles/globals.scss'

import { fontVariables } from '@/lib/font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={fontVariables}>
        <header>アヌアヌ</header>
        <main>{children}</main>
        <footer>© 2021 AnuAnu</footer>
      </body>
    </html>
  )
}
